export const socialMediasData = [
  {
    platform: "facebook",
    social: {
      user_info: {
        name: "Emily Williams",
        username: "emilywilliams123",
        follower_count: 1500,
        following_count: 500,
        profile_picture: "https://example.com/profile_pic.jpg",
      },
      posts: [
        {
          post_id: 1,
          text: "Had a wonderful day with my family! ❤️",
          date: "2024-05-09T18:00:00",
          like_count: 100,
          comment_count: 20,
        },
        {
          post_id: 2,
          text: "Enjoying a movie night with friends! 🎥🍿 #movienight",
          date: "2024-05-06T20:00:00",
          like_count: 120,
          comment_count: 25,
        },
        {
          post_id: 3,
          text: "Feeling grateful for the support of my loved ones! ❤️ #gratitude",
          date: "2024-05-03T12:00:00",
          like_count: 150,
          comment_count: 30,
        },
        {
          post_id: 4,
          text: "Celebrating a friend's birthday! 🎉🎂 #birthday",
          date: "2024-04-30T18:00:00",
          like_count: 180,
          comment_count: 35,
        },
        {
          post_id: 5,
          text: "Exploring new hobbies and interests! 🎨🎸 #hobbies",
          date: "2024-04-27T15:30:00",
          like_count: 100,
          comment_count: 20,
        },
        {
          post_id: 6,
          text: "Grilling barbecue in the backyard! 🍖🔥 #bbq",
          date: "2024-04-24T17:00:00",
          like_count: 120,
          comment_count: 25,
        },
        {
          post_id: 7,
          text: "Family game night with board games! 🎲 #familytime",
          date: "2024-04-21T19:00:00",
          like_count: 140,
          comment_count: 30,
        },
        {
          post_id: 8,
          text: "Visiting a local art exhibition! 🖼️ #artlover",
          date: "2024-04-18T14:00:00",
          like_count: 160,
          comment_count: 35,
        },
        {
          post_id: 9,
          text: "Cooking homemade dinner with fresh ingredients! 🍽️ #homemade",
          date: "2024-04-15T19:30:00",
          like_count: 180,
          comment_count: 40,
        },
        {
          post_id: 10,
          text: "Weekend road trip with friends! 🚗🌄 #roadtrip",
          date: "2024-04-12T08:00:00",
          like_count: 200,
          comment_count: 45,
        },
      ],
    },
  },
  {
    platform: "instagram",
    social: {
      user_info: {
        name: "Jane Smith",
        username: "janesmith123",
        follower_count: 5000,
        following_count: 1000,
        profile_picture: "https://example.com/profile_pic.jpg",
      },
      posts: [
        {
          post_id: 1,
          caption: "Summer is here! 🌞 #vacation",
          date: "2024-05-11T12:00:00",
          like_count: 120,
          comment_count: 25,
          view_count: 1000,
        },
        {
          post_id: 2,
          caption: "Exploring new places! 🌍 #adventure",
          date: "2024-05-09T15:00:00",
          like_count: 80,
          comment_count: 10,
          view_count: 700,
        },
        {
          post_id: 3,
          caption: "Enjoying a cup of coffee on a rainy day! ☕ #cozy",
          date: "2024-05-07T11:30:00",
          like_count: 150,
          comment_count: 30,
          view_count: 1200,
        },
        {
          post_id: 4,
          caption: "Throwback to last summer's vacation! 🏖️ #memories",
          date: "2024-04-30T14:00:00",
          like_count: 200,
          comment_count: 20,
          view_count: 1800,
        },
        {
          post_id: 5,
          caption:
            "Feeling grateful for the little things in life! 🌻 #gratitude",
          date: "2024-04-25T10:45:00",
          like_count: 100,
          comment_count: 15,
          view_count: 900,
        },
        {
          post_id: 6,
          caption: "Sunday vibes! 😊 #relaxing",
          date: "2024-04-20T09:00:00",
          like_count: 120,
          comment_count: 25,
          view_count: 1100,
        },
        {
          post_id: 7,
          caption: "Trying out new recipes in the kitchen! 🍳 #cooking",
          date: "2024-04-15T16:30:00",
          like_count: 90,
          comment_count: 10,
          view_count: 800,
        },
        {
          post_id: 8,
          caption:
            "Nature's beauty never fails to amaze me! 🌿 #naturephotography",
          date: "2024-04-10T13:15:00",
          like_count: 180,
          comment_count: 35,
          view_count: 1500,
        },
        {
          post_id: 9,
          caption: "Happy Friday everyone! 🎉 #weekendvibes",
          date: "2024-04-05T17:00:00",
          like_count: 250,
          comment_count: 40,
          view_count: 2000,
        },
        {
          post_id: 10,
          caption: "Celebrating milestones! 🥳 #achievementunlocked",
          date: "2024-03-31T12:45:00",
          like_count: 300,
          comment_count: 50,
          view_count: 2500,
        },
      ],
    },
  },
  {
    platform: "linkedin",
    social: {
      user_info: {
        name: "Alice Johnson",
        username: "alicejohnson123",
        follower_count: 3000,
        following_count: 800,
        profile_picture: "https://example.com/profile_pic.jpg",
      },
      posts: [
        {
          post_id: 1,
          title: "Working on a new project! 💼",
          content:
            "Great team collaboration! More details of the project coming soon...",
          date: "2024-05-10T14:00:00",
          like_count: 80,
          comment_count: 15,
        },
        {
          post_id: 2,
          title: "Excited to announce a new partnership! 💼",
          content:
            "Thrilled to collaborate with XYZ Company on an innovative project.",
          date: "2024-05-08T16:00:00",
          like_count: 90,
          comment_count: 20,
        },
        {
          post_id: 3,
          title: "Happy to share my recent article! 📝",
          content:
            "Check out my latest blog post on the importance of work-life balance.",
          date: "2024-05-05T12:30:00",
          like_count: 120,
          comment_count: 25,
        },
        {
          post_id: 4,
          title: "Reflecting on career milestones! 🌟",
          content:
            "Grateful for the opportunities and challenges that have shaped my journey.",
          date: "2024-05-02T15:45:00",
          like_count: 150,
          comment_count: 30,
        },
        {
          post_id: 5,
          title: "Attended an inspiring industry event! 🎓",
          content:
            "Key insights and networking opportunities at the conference.",
          date: "2024-04-27T10:15:00",
          like_count: 100,
          comment_count: 15,
        },
        {
          post_id: 6,
          title: "Sharing insights on leadership! 👩‍💼",
          content:
            "Leadership is about empowering others and fostering a collaborative culture.",
          date: "2024-04-24T14:00:00",
          like_count: 110,
          comment_count: 20,
        },
        {
          post_id: 7,
          title: "Grateful for my supportive team! 🙌",
          content:
            "Teamwork makes the dream work! Celebrating achievements together.",
          date: "2024-04-21T11:30:00",
          like_count: 130,
          comment_count: 25,
        },
        {
          post_id: 8,
          title: "Work-life balance: finding harmony! ⚖️",
          content:
            "Prioritizing well-being and productivity in both personal and professional life.",
          date: "2024-04-18T09:00:00",
          like_count: 140,
          comment_count: 30,
        },
        {
          post_id: 9,
          title: "Embracing change and growth! 🌱",
          content:
            "Adapting to new challenges and seizing opportunities for development.",
          date: "2024-04-15T13:00:00",
          like_count: 160,
          comment_count: 35,
        },
        {
          post_id: 10,
          title: "Sharing career advice and insights! 📈",
          content:
            "Leveraging experience to mentor and inspire others in their professional journey.",
          date: "2024-04-12T16:30:00",
          like_count: 180,
          comment_count: 40,
        },
      ],
    },
  },
  {
    platform: "twitter",
    social: {
      user_info: {
        name: "John Doe",
        username: "johndoe123",
        follower_count: 2000,
        following_count: 500,
        profile_picture: "https://example.com/profile_pic.jpg",
      },
      posts: [
        {
          tweet_id: 1,
          text: "What a lovely weather! 🌤️",
          date: "2024-05-11T09:30:00",
          like_count: 50,
          retweet_count: 10,
          reply_count: 5,
        },
        {
          tweet_id: 2,
          text: "Just finished reading an amazing book! Highly recommend it! 📚 #booklover",
          date: "2024-05-08T14:20:00",
          like_count: 70,
          retweet_count: 15,
          reply_count: 8,
        },
        {
          tweet_id: 3,
          text: "Excited to start a new project! 💼 #motivated",
          date: "2024-05-06T11:10:00",
          like_count: 100,
          retweet_count: 20,
          reply_count: 12,
        },
        {
          tweet_id: 4,
          text: "Attended an inspiring conference today! 🌟 #networking",
          date: "2024-05-03T16:45:00",
          like_count: 120,
          retweet_count: 25,
          reply_count: 10,
        },
        {
          tweet_id: 5,
          text: "Morning rituals: exercise, meditation, and a healthy breakfast! 🌅 #selfcare",
          date: "2024-04-28T08:00:00",
          like_count: 90,
          retweet_count: 10,
          reply_count: 5,
        },
        {
          tweet_id: 6,
          text: "Feeling grateful for the opportunities life brings! 🙏 #gratitude",
          date: "2024-04-25T09:30:00",
          like_count: 80,
          retweet_count: 12,
          reply_count: 6,
        },
        {
          tweet_id: 7,
          text: "Weekend getaway to recharge and relax! 🏞️ #weekendvibes",
          date: "2024-04-22T17:00:00",
          like_count: 110,
          retweet_count: 18,
          reply_count: 9,
        },
        {
          tweet_id: 8,
          text: "Attending a workshop on personal development today! 💪 #learning",
          date: "2024-04-19T13:45:00",
          like_count: 150,
          retweet_count: 20,
          reply_count: 15,
        },
        {
          tweet_id: 9,
          text: "Sunday brunch with friends is always a good idea! 🥂 #friends",
          date: "2024-04-16T11:00:00",
          like_count: 200,
          retweet_count: 30,
          reply_count: 20,
        },
        {
          tweet_id: 10,
          text: "Reflecting on the week and setting new goals! 🌟 #goalsetting",
          date: "2024-04-13T14:30:00",
          like_count: 180,
          retweet_count: 25,
          reply_count: 18,
        },
      ],
    },
  },
];
